name       : pinta
version    : 1.6
release    : 6
source     :
    - https://github.com/PintaProject/Pinta/releases/download/1.6/pinta-1.6.tar.gz : f1ea9e95f1051b92c8d8b6f622dfb77bd26254a165a836ec179aae10eb99d881
license    : GPL-2.0 
summary    : Pinta Painting Made Simple
description: |
    Pinta is a free, open source drawing/editing program modeled after Paint.NET. Its goal is to provide users with a simple yet powerful way to draw and manipulate images on Linux, Mac, Windows, and *BSD.
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
    - pkgconfig(mono-addins)
rundeps    :
    - mono
    - mono-devel
    - mono-addins
    - gtk-sharp
setup      : |
    find . -name "*.sln" -print -exec sed -i 's/Format Version 10.00/Format Version 11.00/g' {} \;
    find . \( -name "*.csproj" -o -name "*.proj" \) -print -exec sed -i 's#ToolsVersion="3.5"#ToolsVersion="4.0"#g; s#<TargetFrameworkVersion>.*</TargetFrameworkVersion>##g; s#<PropertyGroup>#<PropertyGroup><TargetFrameworkVersion>v4.5</TargetFrameworkVersion>#g; s#Mono.Posix, Version.*"#Mono.Posix"#g' {} \;
    %configure
build      : |
    %make
install    : |
    %make_install
