name       : pinta
version    : 1.6
release    : 3
source     :
    - https://github.com/PintaProject/Pinta/releases/download/1.6/pinta-1.6.tar.gz : f1ea9e95f1051b92c8d8b6f622dfb77bd26254a165a836ec179aae10eb99d881
license    : GPL-2.0 
summary    : Pinta Painting Made Simple
description: |
    Pinta is a free, open source drawing/editing program modeled after Paint.NET. Its goal is to provide users with a simple yet powerful way to draw and manipulate images on Linux, Mac, Windows, and *BSD. 
rundeps    :
    - mono
    - mono-addins
    - gtk-sharp
builddeps  :
    - pkgconfig(mono)
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono-addins)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
