name       : pinta
version    : 1.7
homepage   : https://pinta-project.com/pintaproject/pinta/
release    : 12
source     :
    - https://github.com/PintaProject/Pinta/releases/download/1.7/pinta-1.7.tar.gz : 678c0d5c6e41da77696180efc71476ccfda3238a3d68d7331198c8a431dbf96c
license    : MIT
component  : multimedia.graphics
summary    : Pinta Painting Made Simple
description: |
    Pinta is a free, open source drawing/editing program modeled after Paint.NET. Its goal is to provide users with a simple yet powerful way to draw and manipulate images on Linux, Mac, Windows, and *BSD.
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
    - pkgconfig(mono-addins)
    - pkgconfig(yelp-xsl)
    - itstool
    - intltool
    - yelp-devel
    - yelp-tools
rundeps    :
    - mono
    - mono-addins
    - gtk-sharp
patterns   :
    - /usr/lib64/pkgconfig
setup      : |
    %configure
build      : |
    %make -j1
install    : |
    %make_install -j1
