name       : pinta
version    : 1.7
homepage   : https://pinta-project.com/pintaproject/pinta/
release    : 8
source     :
    - https://solus-project.com/sources/pinta-1.7.tar.xz : 8485e1df8f3cce1addd3fac8cb7513c82505e6380bf1ec911698dc7451ee791b
license    : MIT
component  : multimedia.graphics
summary    : Pinta Painting Made Simple
description: |
    Pinta is a free, open source drawing/editing program modeled after Paint.NET. Its goal is to provide users with a simple yet powerful way to draw and manipulate images on Linux, Mac, Windows, and *BSD.
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
    - pkgconfig(mono-addins)
    - pkgconfig(yelp-xsl)
    - itstool
    - intltool
    - yelp-devel
    - yelp-tools
rundeps    :
    - mono
    - mono-devel
    - mono-addins
    - gtk-sharp
patterns   :
    - /usr/lib64/pkgconfig
setup      : |
    %autogen
build      : |
    %make -j1
install    : |
    %make_install -j1
